/* INSERTAR DATOS */

INSERT INTO REGISTREDUSERS
VALUES (1, 'Kevin', 'Herrera', 'Kevin16', 'kherrera16@gmail.com ', SYSDATE, SYSDATE);
COMMIT;


/* ELIMINAR DATA */
DELETE REGISTREDUSERS;


/* ELIMINAR TABLA */
DROP TABLE REGISTREDUSERS;

/* SELECCIONAR DATA */
SELECT * FROM REGISTREDUSERS;