/* INSERTAR DATOS */

INSERT INTO REGISTREDUSERS
VALUES (UserId.NEXTVAL, 'Kevin', 'Herrera', 'Kevin16', 'kherrera16@gmail.com', SYSDATE, SYSDATE);

INSERT INTO REGISTREDUSERS
VALUES (UserId.NEXTVAL, 'Roberto', 'Cardenas', 'Beto', 'bcardenas@gmail.com', SYSDATE, SYSDATE);


COMMIT;


/* ELIMINAR DATA */
DELETE REGISTREDUSERS;


/* ELIMINAR TABLA */
DROP TABLE REGISTREDUSERS;

/* SELECCIONAR DATA */
SELECT * FROM REGISTREDUSERS;

--Cración de Secuencias
CREATE SEQUENCE UserId;
COMMIT;