/*CREACIÓN DE TABLA*/
CREATE TABLE Plan_Pago
 (
	ID 		            INT PRIMARY KEY, --PK
	NAME 			        VARCHAR(12) NOT NULL,
	LASTNAME      	  VARCHAR(12) NOT NULL,
	USERNAME			    VARCHAR(12) NOT NULL,
  EMAIL             VARCHAR(50) NOT NULL,
  CREATEDUSER       DATE NOT NULL,
  UPDATEDUSER       DATE NOT NULL 
);
COMMIT;

SELECT * FROM REGISTREDUSERS;